# Permalinks
#
permalink:           pretty

# Setup
title:               typename jon_traits<T>::blog
tagline:             'In templates we trust'
description:         'A blog focused on C++, Embedded, and developer tooling. Big thanks to everyone working on <a href="http://lanyon.getpoole.com" target="_blank">Lanyon</a> for the theme.'
url:                 jontheburger.github.io
baseurl:             ''
paginate:            5

# About/contact
author:
  name:              Jon Povirk
  url:               https://github.com/JonTheBurger
  email:             Jonathan.Povirk@pitt.edu

# Custom vars
version:             1.0.0
